<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>

<div class="breadcrumbs-wrapper">
    <a class="back-button" href="javascript: history.go(-1)"></a>

    <div class="breadcrumbs" data-mage-init='{
        "breadcrumbs": {
            "categoryUrlSuffix": "<?= $block->escapeHtml($viewModel->getCategoryUrlSuffix()); ?>",
            "useCategoryPathInUrl": <?= (int)$viewModel->isCategoryUsedInProductUrl(); ?>,
            "product": "<?= $block->escapeHtml($viewModel->getProductName()); ?>"
        }
    }'>
    </div>

<div class="breadcrumbs-info">
    <div class="phone"><span>04102 804 0</span></div>
    <div class="email"><span>info@kroschke.de</span></div>
</div>

</div>

<script>
    require([
            'jquery'],
        function () {

            jQuery(document).ready(function() {

            });
        });
</script>