<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();

$additionalInformation = $block->getInfo()->getAdditionalInformation();
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php if($block->getMethod()->getCode() === \Kroschke\Debit\Model\Methods\Debit::METHOD_CODE): ?>
        <tr>
            <th>IBAN:</th>
            <td>
                <?= $additionalInformation['iban'] ?>
            </td>
        </tr>
        <?php else: ?>
            <?php foreach ($specificInfo as $label => $value):?>
                <tr>
                    <th><?= $block->escapeHtml($label) ?>:</th>
                    <td>
                        <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php  endif; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
